import React from 'react';
import { View, Text, StyleSheet, Linking, Modal } from 'react-native';
import CloseButton from './CloseButton';

export default function CreditsModal({ visible, onClose }: { visible: boolean; onClose: () => void }) {

    return (
        <Modal visible={visible} animationType="slide" transparent={true}>
            <View style={styles.modalContainer}>
                <View style={styles.modalContent}>
                    <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderColor: 'lightgray', borderBottomWidth: 1, paddingBottom: 10 }}>
                        <Text style={styles.modalTitle}>About</Text>
                        <CloseButton onPress={onClose} />
                    </View>
                    <Text style={styles.modalDescription}>
                        Dream Weather Mobile (U.S. Edition) is a mobile app that provides real-time weather information and fun weather facts. It uses webcam data from OpenWebcamDB, weather data from NOAA/NWS, and fun facts generated by Cohere's language model.
                    </Text>
                    <Text style={styles.modalSubtitle}>
                        Data sources:
                    </Text>
                    <Text style={styles.modalText}>
                        Webcam data: <Text style={styles.link} onPress={() => Linking.openURL('https://openwebcamdb.com')}>OpenWebcamDB</Text>
                    </Text>
                    <Text style={styles.modalText}>
                        Weather data: <Text style={styles.link} onPress={() => Linking.openURL('https://www.weather.gov')}>NOAA/NWS</Text>
                    </Text>
                    <Text style={styles.modalText}>
                        Fun facts: <Text style={styles.link} onPress={() => Linking.openURL('https://cohere.ai')}>Cohere</Text>
                    </Text>
                    <Text style={styles.modalText}>
                        Mountain image by <Text style={styles.link} onPress={() =>
                            Linking.openURL('https://pixabay.com/users/fromsalih-3094244/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=6376016')}>
                            Salih Altuntaş </Text>
                    </Text>
                    <Text style={styles.modalText}>
                        Blue sky image by <Text style={styles.link} onPress={() =>
                            Linking.openURL('https://pixabay.com/users/engin_akyurt-3656355/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=4374619')}>
                            Engin Akyurt </Text>
                    </Text>
                    <Text style={styles.modalText}>
                        Rain image by <Text style={styles.link} onPress={() =>
                            Linking.openURL('https://pixabay.com/users/q839809004-3593939/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1765775')}>
                            q839809004 </Text>
                    </Text>
                    <Text style={styles.modalText}>
                        Snow image by <Text style={styles.link} onPress={() =>
                            Linking.openURL('https://pixabay.com/users/jillwellington-334088/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=6835819')}>
                            Jill Wellington </Text>
                    </Text>
                    <Text>{'\n'}</Text>
                    <Text style={styles.modalText}>
                        App developed by <Text style={styles.link} onPress={() => Linking.openURL('https://github.com/kenzkenzkenz')}>Mackenzie Allen</Text>
                    </Text>
                    <Text style={styles.modalText}>
                        View source code on <Text style={styles.link} onPress={() => Linking.openURL('https://github.com/kenzkenzkenz/dream-weather-mobile')}>GitHub</Text>
                    </Text>
                </View>
            </View>
        </Modal>
    );
}

const styles = StyleSheet.create({
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        width: '80%',
    },
    modalTitle: {
        fontSize: 26,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    modalDescription: {
        fontSize: 16,
        marginTop: 10,
        marginBottom: 15,
    },
    modalSubtitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginTop: 15,
        marginBottom: 5,
    },
    modalText: {
        fontSize: 16,
        margin: 3
    },
    link: {
        color: 'blue',
        textDecorationLine: 'underline',
    },
}); 