import React from 'react';
import { View, Text, StyleSheet, Linking, Modal } from 'react-native';
import CloseButton from './CloseButton';

export default function CreditsModal({ visible, onClose }: { visible: boolean; onClose: () => void }) {

    return (
        <Modal visible={visible} animationType="slide" transparent={true}>
            <View style={styles.modalContainer}>
                <View style={styles.modalContent}>
                    <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderColor: 'lightgray', borderBottomWidth: 1, paddingBottom: 10 }}>
                        <Text style={styles.modalTitle}>Credits</Text>
                        <CloseButton onPress={onClose} />
                    </View>
                    <Text>{'\n'}</Text>
                    <Text style={styles.modalText}>
                        Dream Weather Mobile (U.S. Edition) is a mobile app that provides real-time weather information and fun weather facts. It uses webcam data from OpenWebcamDB, weather data from NOAA/NWS, and fun facts generated by Cohere's language model.
                    </Text>
                    <Text>{'\n'}</Text>
                    <Text style={styles.modalText}>
                        Data sources:
                    </Text>
                    <Text style={styles.modalText}>
                        - Webcam data: <Text style={styles.link} onPress={() => Linking.openURL('https://openwebcamdb.com')}>OpenWebcamDB</Text>
                    </Text>
                    <Text style={styles.modalText}>
                        - Weather data: <Text style={styles.link} onPress={() => Linking.openURL('https://www.weather.gov')}>NOAA/NWS</Text>
                    </Text>
                    <Text style={styles.modalText}>
                        - Fun facts: <Text style={styles.link} onPress={() => Linking.openURL('https://cohere.ai')}>Cohere</Text>
                    </Text>
                    <Text style={styles.modalText}>
                        - Developed by <Text style={styles.link} onPress={() => Linking.openURL('https://github.com/kenzkenzkenz')}>Mackenzie Allen</Text>
                    </Text>
                    <Text style={styles.modalText}>
                        - View source code on <Text style={styles.link} onPress={() => Linking.openURL('https://github.com/kenzkenzkenz/dream-weather-mobile')}>GitHub</Text>
                    </Text>
                </View>
            </View>
        </Modal>
    );
}

const styles = StyleSheet.create({
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        width: '80%',
    },
    modalTitle: {
        fontSize: 26,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    modalText: {
        fontSize: 16,
    },
    link: {
        color: 'blue',
        textDecorationLine: 'underline',
    },
}); 